name: Monitoring URL REPL GitHub
on: 
  schedule:
    - cron: '*/1 * * * *' # Menjadwalkan pengecekan setiap 1 menit
jobs:
  check_repl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check URL REPL status
      run: |
        curl --head --silent ${{secrets.URL}}
        if [ "$?" -eq "0" ]; then
          echo "URL REPL RUN"
        else
          echo "URL REPL NOT RUN"
        fi
